import GlobalProvider from "@/utils/GlobalProvider";
import "./globals.css";
import Script from "next/script";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
       <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9810065319228675"
     crossorigin="anonymous"></Script>

<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9810065319228675"
     data-ad-slot="8567245567"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<Script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</Script>
      </head>
      <body>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
